name: build docs and publish to gh-pages branch

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependency
      run: pip install sphinx_rtd_theme
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: source
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
    - name: Add CNAME
      run: |
        echo "docs.seasalt.ai" >> CNAME

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "Update test.txt"
        git push origin gh-pages